### PR TITLE
Define standard, vendor-agnostic, language-agnostic instrumentation identity attributes

### PR DESCRIPTION
**Pull request by michaelsafyan**
## Changes

Introduces `instrumentation.source.*` and `instrumentation.distribution.*` attributes to enable more triangulation of dependency libraries that have been instrumented with Open Telemetry and that construct the `InstrumentationScope`.

This is forked off from related pull request:

 - https://github.com/open-telemetry/semantic-conventions/pull/1047

The related pull request includes GCP-specific attributes (e.g. `gcp.client.service`). Standard, common attributes were requested there. This pull request aims to provide the general, vendor-agnostic attributes requested.

## Merge requirement checklist

* [X] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [X] Change log entry added, according to the guidelines in [When to add a changelog entry](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md#when-to-add-a-changelog-entry).
  * If your PR does not need a change log, start the PR title with `[chore]`
* [X] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.

### CODE REVIEW

**Comment by joaopgrassi** [comment]
It almost seems like we need general conventions to define packages, package repositories and source code 🤔 .

**Comment by joaopgrassi** [comment]
We discussed this PR in the semantic conventions meeting (2024-06-17). Basically, we see the following issues/points to clarify:

- Several attributes seem similar/relevant to CI/CD for example, `target`, `repo`. We can see those also being use there
- Other attributes look like they also describe a general concept of a "package", like the name of the package, where one can find it. 
- Potential conflicts with scope name,version and artificat name/version

**Comment by lmolkova** [comment]
Related: https://github.com/open-telemetry/semantic-conventions/issues/1229

**Comment by pellared** [comment]
Related: https://github.com/open-telemetry/opentelemetry-specification/pull/4146

**Pull request closed without merging**
