### PR TITLE
Update `jvm.gc.duration` histogram buckets to `[ 0.01, 0.1, 1, 10 ]`

### LINKED ISSUE #274: Should `jvm.gc.duration` histogram have any default buckets?
Currently the `jvm.gc.duration` histogram has this bucket definition:

> This metric SHOULD be specified with
[`ExplicitBucketBoundaries`](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.22.0/specification/metrics/api.md#instrument-advice)
of `[]` (single bucket histogram capturing count, sum, min, max).

Opening this as a tracking issue since it has come up as an open question from the semantic convention working group.

### PR DESCRIPTION
**Pull request by trask**
Fixes #274

Related to #316 

## Changes

Updates `jvm.gc.duration` histogram buckets to `[ 0.01, 0.1, 1, 10 ]`.

## Merge requirement checklist

* [x] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [x] [CHANGELOG.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CHANGELOG.md) updated for non-trivial changes.
* [x] ~[schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.~

### CODE REVIEW

**Review by jack-berg — APPROVED** [review]

**Review by jonatan-ivanov — APPROVED** [review]
I still think we could have more buckets than this but bucketing is hard and I hope we will get some user feedback.

**Comment by trask** [comment]
> I still think we could have more buckets than this (though users can configure this) but bucketing is hard and I hope we will get some user feedback.

are you thinking an additional bucket on the low/high end, or more intermediate buckets?

**Comment by jonatan-ivanov** [comment]
Probably not on the high end, though will there be an implicit +inf bucket too?
But on the low end and in between might be useful not just to have more accurate picture when something is wrong but also when users change something and they are curious about its impact.

**Review by jack-berg — APPROVED** [review]

**Comment by trask** [comment]
Discussed in Java SIG. Consensus is that `[ 0.01, 0.1, 1, 10 ]` is a reasonable minimal set of buckets (keeping processing, transmission and storage costs down), and users can always override based on their specific needs

**Review by AlexanderWert — APPROVED** [review]

**Pull request merged**
