### PR TITLE
Add issue templates and clarify expectations for area experts

### LINKED ISSUE #12: Set up github ISSUE templates
We should create templates for the following:

- [ ] Bug/Issues with current semantic conventions and/or tooling
- [ ] Project proposal for starting new working group in a semantic convention area
- [ ] Feature request for existing semantic convention area (maybe one for each area that have approvers)
- [ ] Feature request for tooling

### PR DESCRIPTION
**Pull request by reyang**
Fixes #12

## Changes

* Improved the format of CODEOWNERS file (removing trailing spaces, indentation, alphabetic sorting)
* Added issue templates
* Added a note in the CODEOWNERS file clarifying how areas and experts can be added.

### CODE REVIEW

**Review by jsuereth — COMMENTED** [review]
I think perhaps I have two major comments here:

1. Instead of just a request to add-experts, we should have a bug template about adding a *new area* that looks similar to the project workflow in community.  EIther a specific template for it that outlines what to do *or* call out more in feature telmplate that you should NOT be requesting new areas here.
2. For Feature request, we should have some language around understanding:
  - Is this a new area?
  - Is it against a stable specification?

**Comment by joaopgrassi** [comment]
I think we split this into small chunks so we have something. The current bulk of changes are basically around changing or adding things to existing conventions and stabilization.

Could we start small with at least Issue templates for them with things like:

### Bugs

  - Describe the bug
  - Area (from `model/registry`) -> somehow select automatically, if not from registry add `OTHER` or smt
  - What did you expect/what did you see instead?
  - Which version
  - Additional context
  
  
### Propose changes in existing conventions

  - Describe the change. Is it related to a problem?
  - Area (from `model/registry`) -> somehow select automatically, if not from registry add `OTHER` or smt
  - Describe proposed solution
  - Describe alternatives considered (if any)
  - Additional context
  
### Propose new conventions

  - Describe the new convention
  - Area (from `model/registry`) -> if not existing, this can also be used to kick start a new one. So use `NEW` or something
  - Describe proposed solution
  - Describe alternatives considered (if any)
  - Additional context

WDYT?

**Comment by joaopgrassi** [comment]
We can pretty much base on what the folks in the collector contrib are doing. They use GH form template for issues, and even auto generate the "components" based on the files https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/ISSUE_TEMPLATE/feature_request.yaml?plain=1#L14.

We could do the same, and use the files in the `model/registry` folder. Also add matching labels for those.

**Comment by jsuereth** [comment]
@joaopgrassi I really like your proposal here.  Would you be willing to close this PR and put your proposal into a new PR to replace it?

**Comment by joaopgrassi** [comment]
> @joaopgrassi I really like your proposal here. Would you be willing to close this PR and put your proposal into a new PR to replace it?

I would be very interested in taking this over. Can't promise I will do it right away though, but I will try to squeeze it in :)

**Comment by joaopgrassi** [comment]
There's also this proposal from @jack-berg which is awesome https://github.com/open-telemetry/opentelemetry-specification/issues/3821. I think we can also align to that in some shame or form, given both repos are "similar".

**Comment by joaopgrassi** [comment]
Closing this in favor of https://github.com/open-telemetry/semantic-conventions/pull/777

**Pull request closed without merging**
