### PR TITLE
Add enum value separators

### PR DESCRIPTION
**Pull request by dyladan**
Add separators in order to separate enum value tables from the footnotes above.

Fixes https://github.com/open-telemetry/semantic-conventions/issues/1569

### CODE REVIEW

**Comment by jsuereth** [comment]
@dyladan I really like this.  Is this in DRAFT for discussion or other reasons?

**Comment by dyladan** [comment]
There are two versions of it if you look at the linked issue. I didn't want to go through the hassle of keeping two PR's up-to-date before we decided which one we would rather use.

**Review by lmolkova — APPROVED** [review]

**Review by trask — APPROVED** [review]
approving, I'm happy with either approach, much better than current state, thanks!

**Comment by dyladan** [comment]
image

even git is confused about the separations 😆

**Pull request merged**
