### PR TITLE
describe JVM CPU metrics

### PR DESCRIPTION
**Pull request by zeitlinger**
Successor of https://github.com/open-telemetry/opentelemetry-specification/pull/3487

### CODE REVIEW

**Comment by Oberon00** [comment]
Checks did complete successfully: https://github.com/open-telemetry/semantic-conventions/actions/runs/4959486530/jobs/8873655841?pr=13

Is there a reference to this from markdown anywhere? Probably there should be?

**Comment by jack-berg** [comment]
Ah interesting. It looks like `note` field on attributes manifests as footnotes but nothing happens with the `note` field on metrics. Ignore my comment for this PR - this appears to be an enhancement needed for [build-tools](https://github.com/open-telemetry/build-tools/tree/main/semantic-conventions#markdown-tables).

**Comment by Oberon00** [comment]
Yes, it might be related to https://github.com/open-telemetry/build-tools/issues/15

**Review by jsuereth — APPROVED** [review]
Approved.  I think we'll need to bump the semconv tooling to get this to show up in the future, but orthogonal to the fix. 

Thanks for submitting!

**Review by reyang — APPROVED** [review]

**Review by trask — APPROVED** [review]

**Comment by zeitlinger** [comment]
> @zeitlinger would you mind adding to changelog? Then we can merge

done

**Review by jsuereth — APPROVED** [review]

**Pull request merged**
