### PR TITLE
Update `user_agent.*` wording to support multiple apps

### LINKED ISSUE #662: Expand user agent to support more applications, not only browser
This is a follow up for https://github.com/open-telemetry/semantic-conventions/pull/452 
Currently we support only browser for name/version fields inside user-agent namespace and we should discuss and implement a way to support other applications (for example gRPC). 
I suggest to change the description to support "most  important" or "most dominant" app if there are many apps available in user-agent string to be more inclusive

### PR DESCRIPTION
**Pull request by trisch-me**
Fixes #662

## Merge requirement checklist

* [x] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [x] [CHANGELOG.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CHANGELOG.md) updated for non-trivial changes.
* [ ] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.

### CODE REVIEW

**Review by trask — COMMENTED** [review]
> such as microservices with multiple applications

I didn't really follow, what would be an example this? thx

**Comment by joaopgrassi** [comment]
Hi @trisch-me !

We changed how the CHANGELOG.md is managed. Please take a look at https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md#adding-a-changelog-entry to see what needs to be done. Sorry for the disruption.

**Comment by trisch-me** [comment]
hey @joaopgrassi I haven't updated the changelog because it's only a new wording without bigger changes. Please let me know if you think I need to create a new entry for this PR

**Review by trask — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Comment by trisch-me** [comment]
@joaopgrassi The same problem as in your recent PR (with WIP label), I don't have changes for changelog for this trivial PR but the job is failing and I don't have access to the labels in my current role.

**Comment by arminru** [comment]
> @joaopgrassi The same problem as in your recent PR (with WIP label), I don't have changes for changelog for this trivial PR but the job is failing and I don't have access to the labels in my current role.

@trisch-me You can prefix the PR title with `[chore]` for the same effect but a changelog entry for the refinement and added note would be fine too I think.

**Comment by trisch-me** [comment]
@arminru I will add changelog entry but I think we need to update our rules as well. There are editorial PRs etc, we could add labels automatically using [github actions](https://github.com/open-telemetry/semantic-conventions/pull/685#issuecomment-1927447668)

**Comment by arminru** [comment]
> @arminru I will add changelog entry but I think we need to update our rules as well. There are editorial PRs etc, we could add labels automatically using [github actions](https://github.com/open-telemetry/semantic-conventions/pull/685#issuecomment-1927447668)

For editorial PRs, if either the PR title is prefixed with `[chore]` or the `Skip Changelog` label is added, the check will pass.

Since merging is always done by a person and not a workflow, that person can just add the label as the very last action right before merging the PR (or the PR author themselves adds the PR title prefix). Until merging it's not an issue if that one merge check fails except for the visual cue it carries.

**Review by pyohannes — APPROVED** [review]

**Pull request merged**
