### PR TITLE
Remove prefix in yaml, add policy check to block future usages (and minor cleanups)

### LINKED ISSUE #1292: Stop using prefix to define attributes
Attributes can be defined in two equivalent ways.

E.g. `foo.bar` can be defined with prefix `foo` and id `bar`

```yaml
group:
- id: foo
  prefix: foo
  attributes: 
  - id: bar
```

or

without prefix and id `foo.bar`

```yaml
group:
- id: foo
  attributes: 
  - id: foo.bar
```

Using prefix is inconvenient:
- when searching for attribute definition in yaml files
- when reading yaml definitons, it's not obvious what the full attribute name would be generated
- tooling needs to resolve full attribute name and we need to be aware of it in some cases when writing policy checks, writing jq filters, generating code

Removing prefix would keep all MD files intact, but would resolve these inconveniences without any obvious downsides.

### PR DESCRIPTION
**Pull request by lmolkova**
## Changes

Related to #1292 - this PR does not block anyone from using prefix, only changes the current pattern.

- Changes all attribute definitions to use fully qualified attribute names and removes all prefixes
- Add rego policy to detect and fail when prefix is used.
- Removes (ignored) `allow_custom_values` on enums

## Merge requirement checklist

* [x] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [x] Change log entry added, according to the guidelines in [When to add a changelog entry](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md#when-to-add-a-changelog-entry).
  * If your PR does not need a change log, start the PR title with `[chore]`
* [x] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.

### CODE REVIEW

**Review by LikeTheSalad — APPROVED** [review]

**Review by joaopgrassi — APPROVED** [review]

**Comment by lmolkova** [comment]
@trisch-me great point. This would be a blocker to #1292 and tooling changes https://github.com/open-telemetry/weaver/issues/263. 

I still want to proceed with this PR since it does not stop someone from using prefix now (when necessary) or tooling from introducing any changes that can still leverage the prefix.

**Comment by trisch-me** [comment]
actually it does break it - as soon as prefix will be added because someone needs it the resolved registry with current weaver will double the prefix, so it will be `prefix.prefix.attribute`. I think this PR should go along together with weaver PR to NOT include prefix into resolved name anymore

**Comment by trisch-me** [comment]
>  whoever adds it, would remove it from the attribute id to not break things 

but then it is inconsistent. If we have decided to be explicit and provide prefix always in the id we need to update instrumentation as well so in case prefix would be there it will not break. Therefore I propose to merge this PR only together with/after weaver PR. 

If you want I can create a PR in weaver which does this job but I'm against merging this PR until tooling is ready.

**Comment by lmolkova** [comment]
> but then it is inconsistent. If we have decided to be explicit and provide prefix always in the id we need to update instrumentation as well so in case prefix would be there it will not break.

it's already inconsistent. Check out deprecated attributes in the registry. All the tooling is agnostic to where the prefix is today. Instrumentations use fully qualified name (prefix + id). 

I'm ok waiting for the tooling changes. I'm trying to explain that this PR does not change status quo.

**Review by trask — APPROVED** [review]
this seems like a good incremental progress to me

**Comment by trisch-me** [comment]
> Instrumentations use fully qualified name (prefix + id) 
this is where I see things are breaking. Because if someone adds a prefix back because it's needed for other functionality, all id's in that group will be wrong or should be updated again to not have prefix in them. So better to remove dependency on prefix for name resolution

**Review by jsuereth — APPROVED** [review]

**Review by adrielp — APPROVED** [review]

**Comment by lmolkova** [comment]
discussed at the tooling wg call 
- it's important to make a consistent choice and, if the decision is to stop using prefix, to stop using it.
- we can prohibit using prefix with rego policy - will add one in this PR
- schema and tooling updates can happen after migration to weaver.

@trisch-me wanted to double-check if you're ok with it.
The embed design does not seem depend on it anymore (#1264), but If it we end up needing it, we can always roll back this PR (partially or fully) - this is another benefit of enforcing it in the policy for now and not (yet) in the tooling.

**Review by trisch-me — APPROVED** [review]
thank you @lmolkova 
With concrete goal to deprecate prefix I approve this PR

**Pull request merged**
