### PR TITLE
Make thread.name and thread.id sampling_relevant

### PR DESCRIPTION
**Pull request by heyams**
cc @trask

### CODE REVIEW

**Review by trask — APPROVED** [review]
can you add a change log entry?

**Comment by Oberon00** [comment]
This would prevent setting these attributes from a OnStart callback, which IMHO would be the most convenient way to implement these.

Maybe we should instead clarify, or implementations can guarantee on their own, that the sampler is called on the starting thread, so that it can access tgis information not from span attributes but directly from the runtime.

**Comment by lmolkova** [comment]
Do we expect instrumentations to add thread attributes? I assumed the more general way to do it is via the processor.

Also, a sampler that would like to use thread information could use the current thread id/name - samples should run synchronously.

**Review by Oberon00 — CHANGES_REQUESTED** [review]
Based on above comments, I think this should not be added.

Instead, a trace SDK spec change could be introduced to guarantee / document per implementation whether samplers are called synchronously.

**Comment by jsuereth** [comment]
I agree w/ @Oberon00 here.  This requires a spec/sampler fix.

**Comment by heyams** [comment]
I will add thread attributes in the sampler per https://github.com/open-telemetry/semantic-conventions/pull/213#pullrequestreview-1556820926 . Thanks!

**Pull request closed without merging**
