### PR TITLE
Update build-tools version to 0.25.0 and add `display_name` to all registry attribute groups

### LINKED ISSUE #978: Add `name` property on registry attribute groups
In order to automatically render readable titles for generated attributes registry docs, it would be useful to have display names for attribute groups in the YAML files (see https://github.com/open-telemetry/semantic-conventions/pull/917#discussion_r1580512059).

Proposal is to add a property `name` (or `display_name` or `title`) to each attributes group in the registry so that the weaver can use that property for rendering headings. 

Example:

```

groups:
  - id: registry.aws.dynamodb
    prefix: aws.dynamodb
    type: attribute_group
    name: AWS DynamoDB
    brief: >
            This document defines attributes for AWS DynamoDB.
    attributes:
         ...
```

### PR DESCRIPTION
**Pull request by AlexanderWert**
Fixes #978

### CODE REVIEW

**Comment by AlexanderWert** [comment]
Depends on: https://github.com/open-telemetry/build-tools/pull/316

**Review by trisch-me — APPROVED** [review]
thanks for quick implementing it. @jsuereth could add this now into the final PR to populate correct name

**Review by ChrsMark — APPROVED** [review]
LGTM

**Comment by trisch-me** [comment]
One question though - should we enforce then a presence of this property for registry?

**Comment by AlexanderWert** [comment]
> One question though - should we enforce then a presence of this property for registry?

yeah, I guess we could extend https://github.com/open-telemetry/build-tools/pull/316 to include it in the validity checks

**Review by lmolkova — APPROVED** [review]
Could you please create an issue to update schema definition (or just update the schema definition) in the https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/semconv.schema.json to include it?

We want to move it to this repo https://github.com/open-telemetry/semantic-conventions/issues/916, but it's not done yet

**Review by noahfalk — APPROVED** [review]
LGTM

**Comment by noahfalk** [comment]
@JamesNK (Just fyi - This looks like a minor cosmetic change)

**Comment by jsuereth** [comment]
> One question though - should we enforce then a presence of this property for registry?

Once we get the rule-engine/checker working in weaver, this is a simple configuration for semantic-conventions.  Let's see if we can get that prioritized as a the next feature we need from weaver for semconv.

**Review by jsuereth — APPROVED** [review]
Thanks for adding all of these.

We need to update both build-tools and weaver.  I merged your build-tools change (will need a release) but we'll also need to update weaver.

Since the weaver PR merged, you should be able to actually update the weaver `attribute_group.md.j2` template to *use* this value in this PR.

**Comment by AlexanderWert** [comment]
> Could you please create an issue to update schema definition (or just update the schema definition) in the https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/semconv.schema.json to include it?

Done, see: https://github.com/open-telemetry/build-tools/pull/317

**Review by joaopgrassi — APPROVED** [review]

**Comment by AlexanderWert** [comment]
> Since the weaver PR merged, you should be able to actually update the weaver `attribute_group.md.j2` template to _use_ this value in this PR.

@jsuereth Done with the last commit.

**Comment by lmolkova** [comment]
@AlexanderWert I think you need to run `make table-generation` to re-generate registry MD files with display name.

**Comment by jsuereth** [comment]
@AlexanderWert Yes - I think that change (and propagation of its value) should be what you need to do in weaver.

There's also a TemplateGroup: https://github.com/open-telemetry/weaver/blob/main/crates/weaver_forge/src/registry.rs#L29 

Once you have Group / TemplateGroup updated and wired - we can immediately start rendering this attribute in the registry.

**Comment by joaopgrassi** [comment]
I added the new field `display_name` to Weaver https://github.com/open-telemetry/weaver/pull/202. So when we have a new weaver release we can go further with this. 

The only thing is: Should we mark the new field as required? The Jinja template now assumes it is but if one attribute group misses it the md rendering will fail (I think).

**Comment by AlexanderWert** [comment]
> The only thing is: Should we mark the new field as required? The Jinja template now assumes it is but if one attribute group misses it the md rendering will fail (I think).

Can we make it required only for registry attribute groups?

**Comment by trisch-me** [comment]
we can enforce through the policies that this attribute is required for registry

**Comment by joaopgrassi** [comment]
>Can we make it required only for registry attribute groups?

Hum I think not, specially in the JSON schema but also on Weaver. What we can do is in the jinja template we check if display name exists and if not, we use the old behavior. I gave that a try and it worked for me locally.

**Comment by joaopgrassi** [comment]
> we can enforce through the policies that this attribute is required for registry

Ah really? Then forget my comment above 👍

**Comment by trisch-me** [comment]
> Then forget my comment above

but until we have it implemented we can just use the workaround you proposed

**Comment by joaopgrassi** [comment]
@AlexanderWert are you able to continue this work, or should one of us take over?

**Comment by AlexanderWert** [comment]
> @AlexanderWert are you able to continue this work, or should one of us take over?

I'll update the PR with your proposal

**Comment by AlexanderWert** [comment]
@joaopgrassi updated this PR

I think we need both releasing and updating the weaver version AND build tools, right?

**Comment by joaopgrassi** [comment]
> I think we need both releasing and updating the weaver version AND build tools, right?

Weaver for sure we need a new release. For build-tools I'm not sure.. but I assume we might (maybe bcs of the JSON schema?)

@lquerel can we have a new Weaver release?

**Comment by lmolkova** [comment]
Oh, I think we still need a build-tools release for this.

**Comment by lquerel** [comment]
> > I think we need both releasing and updating the weaver version AND build tools, right?
> 
> Weaver for sure we need a new release. For build-tools I'm not sure.. but I assume we might (maybe bcs of the JSON schema?)
> 
> @lquerel can we have a new Weaver release?

@joaopgrassi The release v0.5.0 of Weaver contains this feature.

**Comment by joaopgrassi** [comment]
Yes, we have the release and already updated Weaver version in semconv. @AlexanderWert will update the PR because it needs some changes before merging.

**Comment by AlexanderWert** [comment]
@joaopgrassi @lmolkova @lquerel 
Updated my PR.

PTAL, I also changed the order of the generated groups to make sure deprecated attributes are always listed at the end (instead of pure alphabetical order)

**Comment by AlexanderWert** [comment]
@lmolkova The compatibility check still fails.

That has been actually fixed in these PRs, but we did not have a build-tools release since then:
https://github.com/open-telemetry/build-tools/pulls?q=is%3Apr+display_name+is%3Aclosed

So, we need to do a new release of the build tools and update it here.

**Comment by lmolkova** [comment]
@AlexanderWert build-tools v0.25.0 were just published, could you try updating? Thanks!

**Pull request merged**
