### PR TITLE
[chore] Fix Weaver make commands

### LINKED ISSUE #994: `make table-generation` is broken on Windows (Git Bash) after the switch over to weaver
### Area(s)

area:other

## Steps to Reproduce (if any)

Run `make table-generation` on Windows using Git Bash

## Expected Result

Success 😄

## Actual Result

```
✖ IO error for operation on C:/Program Files/Git/source: No such file or directory (os error 2)
make: *** [Makefile:98: table-generation] Error 1
```

### Semantic convention version

main

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by joaopgrassi**
Fixes #994

## Changes

Make Weaver make commands work again in Windows Git bash

## Merge requirement checklist

* [ ] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [ ] Change log entry added, according to the guidelines in [When to add a changelog entry](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md#when-to-add-a-changelog-entry).
  * If your PR does not need a change log, start the PR title with `[chore]`
* [ ] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.

### CODE REVIEW

**Comment by joaopgrassi** [comment]
@trask can you try this see if it works for you? Works on my machine now 😅

**Review by lmolkova — APPROVED** [review]

**Review by jsuereth — APPROVED** [review]

**Review by pyohannes — APPROVED** [review]

**Comment by joaopgrassi** [comment]
Going to merge this. @trask feel free to re-open the issue if it still doesn't work for you.

**Review by trisch-me — APPROVED** [review]
does it still work for linux/mac without `""`?

**Comment by joaopgrassi** [comment]
> does it still work for linux/mac without `""`?

Yep, worked for me on Ubuntu at least.

**Review by trask — APPROVED** [review]
thanks!

**Pull request merged**
