### PR TITLE
[chore] Fixed a dead link for machine id man page

### PR DESCRIPTION
**Pull request by gyliu513**
Fixes #

## Changes

This is fixing a CI error here https://github.com/open-telemetry/semantic-conventions/actions/runs/11861560247/job/33059139725?pr=1574

@lmolkova ^^

Please provide a brief description of the changes here.

Note: if the PR is touching an area that is not listed in the [existing areas](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/README.md), or the area does not have sufficient [domain experts coverage](https://github.com/open-telemetry/semantic-conventions/blob/main/.github/CODEOWNERS), the PR might be tagged as [experts needed](https://github.com/open-telemetry/semantic-conventions/labels/experts%20needed) and move slowly until experts are identified.

## Merge requirement checklist

* [ ] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [ ] Change log entry added, according to the guidelines in [When to add a changelog entry](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md#when-to-add-a-changelog-entry).
  * If your PR does not need a change log, start the PR title with `[chore]`
* [ ] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Comment by trask** [comment]
hi @gyliu513! it looks like you need to also update it in the yaml file

**Review by lmolkova — APPROVED** [review]

**Comment by gyliu513** [comment]
@trask which yaml file you are mentioning, can you point that out? Thanks!

**Comment by trask** [comment]
oh, looks like it's in 3 places: https://github.com/search?q=repo%3Aopen-telemetry%2Fsemantic-conventions+freedesktop&type=code

**Comment by gyliu513** [comment]
@trask done, thanks!

**Pull request merged**
