### PR TITLE
Clarify stabilization plan does not just apply to attributes

### PR DESCRIPTION
**Pull request by alanwest**
Clarification inspired by the following discussion https://github.com/open-telemetry/opentelemetry-dotnet/pull/4766#discussion_r1300370859.

This text shows up in a lot of places. I can update them all, but wanted to get an initial review of the text here before I copy it everywhere. I assume this will not need to be updated in the specification repo once https://github.com/open-telemetry/opentelemetry-specification/pull/3667 is merged.

@trask

### CODE REVIEW

**Review by jsuereth — APPROVED** [review]

**Review by trask — APPROVED** [review]
❤️

**Review by jack-berg — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by joaopgrassi — APPROVED** [review]

**Comment by Oberon00** [comment]
I think this is inconsistent with other wording we have elsewhere that says that semantic conventions only encompass the attribute keys and nothing else.

**Comment by bryannaegele** [comment]
@Oberon00 on don't think that's accurate. That doc says `Semantic Conventions defines the set of fields in the OTLP data model:` and notes properties such as `The span name` under tracing. I don't see where it says it only encompasses attribute keys. Conventions for values are noted there.

**Comment by alanwest** [comment]
> I don't see where it says it only encompasses attribute keys.

Me either... it seems this section in particular is pretty exhaustive: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md#semantic-conventions-stability.

@Oberon00 is there specific wording you're referring to that could be improved?

**Comment by Oberon00** [comment]
You are right it encompasses quite a bit, but critically it does not encompass the attribute values or types. And we can have stricter requirements for this special case anyway.

**Review by Oberon00 — APPROVED** [review]

**Comment by alanwest** [comment]
Given the good number of approvals, shall I update the rest of the files in this PR with this updated text?

**Comment by trask** [comment]
> Given the good number of approvals, shall I update the rest of the files in this PR with this updated text?

👍

**Review by joaopgrassi — APPROVED** [review]

**Pull request merged**
