### PR TITLE
Extend GenAI system to support IBM Watsonx AI and AWS Bedrock

### PR DESCRIPTION
**Pull request by gyliu513**
Added IBM Watsonx AI and AWS Bedrock to the list of possible values that the `gen_ai.system` attribute can take.

## Changes

The following are added:

- IBM Watsonx AI
- AWS Bedrock

Please provide a brief description of the changes here.

Note: if the PR is touching an area that is not listed in the [existing areas](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/README.md), or the area does not have sufficient [domain experts coverage](https://github.com/open-telemetry/semantic-conventions/blob/main/.github/CODEOWNERS), the PR might be tagged as [experts needed](https://github.com/open-telemetry/semantic-conventions/labels/experts%20needed) and move slowly until experts are identified.

## Merge requirement checklist

* [X] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [x] Change log entry added, according to the guidelines in [When to add a changelog entry](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md#when-to-add-a-changelog-entry).
  * If your PR does not need a change log, start the PR title with `[chore]`
* [x] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.

### CODE REVIEW

**Comment by gyliu513** [comment]
@lmolkova @lzchen can you help review? I want to start the process of contributing watsonx to genai instrumentation, thanks!

**Review by lmolkova — APPROVED** [review]
Thank you!

**Comment by lmolkova** [comment]
@open-telemetry/semconv-genai-approvers please take a look

**Review by drewby — APPROVED** [review]
Looks good to me.

**Comment by gyliu513** [comment]
@lmolkova do you know when this will be reflected to https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/gen_ai_attributes.py ? Thanks

**Comment by lmolkova** [comment]
@gyliu513 we'll need to release the new version of semconvs first. We're due for release, but with KubeCon we got behind and it might take 1-2 weeks.

Then someone (usually me, but can be anyone else) needs to regenerate code in https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions.

**Comment by mxiamxia** [comment]
Hi, is there a convention for specifying GenAI attribute values or, more generally, in OpenTelemetry? For instance, `_` is used  as delimiter in AWS service attribute values, like `aws_sqs` in Java SDK below. And this proposal uses `aws.bedrock`. Is it more preferred way to use `.` delimiter for  gen_ai.system attribute specifically?

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/c6a6fa622465ebf931ed5860987cb0ecc6a04a16/instrumentation/aws-lambda/aws-lambda-events-2.2/library/src/main/java/io/opentelemetry/instrumentation/awslambdaevents/v2_2/internal/SqsEventAttributesExtractor.java#L23

**Comment by gyliu513** [comment]
@mxiamxia I think there is no standard for this yet, you may also see that vertex ai is using `vertex_ai`.  Do you want to change the value to `aws_bedrock`?

@lmolkova I think it will be great if we can keep consistent for all LLM platforms, like what is the recommended delimiter for the attribute values.

**Comment by lmolkova** [comment]
`.` should be used by default. `_` should be used to separate words that make no sense without each other - https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/attribute-naming.md

Think about it as namespaces in the code. There could be a lot of different things in `aws` namespace, so `aws.bedrock`, but it'd be `rate_limiting` instead of `rate.limiting`. 

It took us a bit to come up with this rule of thumb, so you might see a lot of examples in the repo that don't follow this patter yet (or not worth breaking). Anyway, we try to follow this pattern for everything new.

**Comment by mxiamxia** [comment]
Thank you all for the response. AWS Observability team is working on supporting AWS Bedrock in CloudWatch by adhering to the OpenTelemetry LLM [Spec](https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-spans/). We will follow the aligned pattern and collaborate with you to contribute the relevant changes in OTel SDKs.

**Pull request merged**
